lapras-inc/lapras-frontend

- src/components/Icon/Icon.vue
他のfunctionalコンポーネントでこのコンポーネントを使う場合、一番外側の要素にdata-v-xxxの属性がつかず、scopedにしているstyleが当たらない問題が発生しました。
そこで、スタイルを当てたい要素をひとつネストさせることで解決しました。
> [fix] 他のfunctionalコンポーネントから使えないバグ修正

- src/components/Modal/Modal.stories.mdx
- src/components/Modal/Modal.vue
背景のクリックでcloseさせるためにつけているクリックイベントが、コンテンツ部分をクリックしたときにも発火しないように、コンテンツ部分のクリック `stopPropagation` しているのですが、それを指定する部分に @click.prevent しているのが原因でした。
preventを外したら動作することを、chrome、safari、firefooxで確認しました。
> モーダル内でリンクが無効になるバグ修正

- src/assets/images/avatar_default.svg
- src/components/AvatarImg/AvatarImg.vue
importされたときにAvatarのデフォルト画像のパスがリンク切れを起こすので、そこまで画像のコード量も多くないため、一旦base64変換したものを.vueに埋め込んで対応。
（外部の画像ファイルをうまく繋ぎ込む方法を @tkow さんに調査いただいています 🙇 ）
> [fix] Avatarのデフォルト画像が正しく表示されない

- src/components/ShortModal/ShortModal.vue
上にスペースがなかったので広げました。
iOSのChrome最新版で x ボタンが押せること確認しました 🙇🏿 
https://github.com/lapras-inc/scouty/issues/9892
> [fix] LAPRAS - スマホでTagを非表示にしようとしたときに出るモーダルの x ボタンが効かない(または推しにくくて押せていない)

- src/components/ProtectedLink/ProtectedLink.stories.mdx
- src/components/ProtectedLink/ProtectedLink.vue
re lapras-inc/scouty#10930
`target="_blank"` のときは `rel="noopener"` がつくようにして、タブナビング対策する
> feat(protectedlink): 別タブで開くときは rel="noopener" をつける

- src/components/ProtectedLink/ProtectedLink.vue
渡されたhrefが大文字だったときにundeifnedになってしまう問題を修正しました。
> feat(protectedlink): HTTPSのような大文字リンクを不要に削除しない

- src/components/Modal/Modal.vue
以前は、モーダルのフィルター（薄い青の部分）の div が、モーダルのコンテンツも内包していました。
フィルターをクリックした際に `$emit('close')` するのですが、コンテンツをクリックした時にはそうならないように `event.stopPropagation` で止めていました。
しかしこれにより、不必要にイベントを殺してしまい、このコンポーネントが使われている箇所で仕掛けた別のイベントも効かなくなってしまう問題がありました。
そこで、フィルター部分とコンテンツ部分を分けることで、 `event.stopPropagation` しない構造にしました。
> fix(modal): modal の DOM 構造を修正し event.stopPropagation を使わないようにした

- src/components/Modal/Modal.vue
読み込み側でエラーが出ていたので、急遽 https://github.com/lapras-inc/lapras-frontend/pull/139 のリファクタを戻しました
内容としては、 setup 関数の中で watch が使えないようでして、それを戻しました。
composition-api のバージョンを変えるなどでいけそうな気もしますが、一旦暫定の対応としてご確認お願いいたします。
> fix(modal): setup 関数内で watch() を使わないようにする

- src/components/TextInput/TextInput.vue
#134 で v-on に外から触れるようにした際に、既存の v-on:input で仕掛けたイベントが2重に呼ばれてしまう不具合があったので、修正しました
これまで v-on:input のペイロードは入力値だったのに対して、 #134 以降はイベントが降ってくるように変わってしまい、 v-model が使えない状態になっていた。
- http://localhost:6006/?path=/story/textinput--default-story
> fix(textinput): v-on:input が使えなくなっていたので修正

- .gitignore
- package.json
- src/components/TextInput/TextInput.vue
- src/components/Tooltip/Tooltip.vue
- src/installCompositionApi.ts
- src/main.ts
- yarn.lock
lapras-frontendの最新版をLAPRAS、Scoutyで読み込むと以下エラーが発生する件の修正
```
[vue-composition-api] must call Vue.use(plugin) before using any function.
```
詳細はコードにコメントします
> 最新のlapras-frontendをLAPRAS, Scoutyで取り込めない件の修正

- src/components/ShortModal/ShortModal.vue
fix: https://github.com/lapras-inc/scouty/issues/13906
ShortModal で content の click イベントを stopPropagation してしまっていたため、issue にある Clipboard のようにイベントが body まで propagate されることを期待しているような処理がうまく機能しなくなっていました。
(このコンポーネントは tajima が作ったらしいのですが) あまりよく覚えていないんですが、多分 overlay と close ボタンの双方に click のハンドラを仕掛けるところを、横着して親にのみ click のハンドラをしかけて、代わりに content の click イベントを stopPropagation する、という阿呆なことをしていたみたいです。
横着しないようにしました。
lapras 側に無理矢理組み込んで issue になっているコピー機能が正常に機能することを確認しました。
> fix(component): shortModal で click を stopPropagation しない

- .github/workflows/npm-release-legacy.yml
- README.md
`legacy-main`を`legacy-relese`に手動でマージすると自動でリリースされるようにしました。
`release`ブランチはバージョンが`0.1.x`, `legacy-release`ブランチは`0.0.x`になっているので、バージョンがぶつかることは無いと思います。
> ci: vue2.7の入ってないブランチでもリリースできるようにする

- vue.config.js
https://github.com/lapras-inc/lapras-frontend/issues/204
vue-cliを5系に上げたことで、アセットのパスの頭に`/`が付くようになり、アセットの解決ができなくなっていた
`publicPath`を設定し、`/`が付かないようにした。
> ビルドがおかしくなっていたのを修正 

- src/components/Modal/Modal.vue
https://github.com/lapras-inc/lapras-frontend/issues/207
- 周りにクリックしても閉じないpadding領域があったのをmarginに変更
- 閉じる×ボタンの右側の領域も押せなかったので修正
> モーダルの外側にクリックしても反応しない領域があったのを修正

- src/components/AvatarImg/AvatarImg.vue
- src/components/Card/Card.vue
- src/components/CheckBox/CheckBox.vue
- src/components/EnhancedIconButton/EnhancedIconButton.vue
- src/components/FieldGroup/FieldGroup.vue
- src/components/FlatButton/FlatButton.vue
- src/components/Icon/Icon.vue
- src/components/Radio/Radio.vue
- src/components/RatingBar/RatingBar.vue
- src/components/TagLabel/TagLabel.vue
- src/components/TextInput/TextInput.vue
- src/components/ToggleSwitch/ToggleSwitch.vue
- src/components/Tooltip/Tooltip.vue
https://github.com/lapras-inc/lapras-frontend/issues/203
※ 詳しくはIssue参照
- `v-bind="attrs"`を使っているコンポネに`inhertAttrs: false`を付与
- v-bindが一番上に書かれていない要素の修正（[参考](https://v3.ja.vuejs.org/guide/migration/v-bind.html#_2-x-%E3%81%A6%E3%82%99%E3%81%AE%E6%A7%8B%E6%96%87)）
- contextをreturnしてtemplate内で使っているところを修正
修正した各コンポーネントの動作をStorybookで確認
まだ本番リリースされないのでザッとで大丈夫です！
`inheritAttrs: false`にしても、クラスやスタイルはVue2では自動でルート要素に受け継がれていたのですが、Vue3ではそれがなくなりました。
そのため、コンポーネントにクラスをつけたりしているところで崩れが生じる可能性がありますが、それはまあ後で直せばいいと思います
[参考](https://v3.ja.vuejs.org/guide/migration/attrs-includes-class-style.html)
> inheritAttrs: falseの付与 & attrsの取り方を変える

- src/components/CheckBox/CheckBox.vue
With disabled option, the CheckBox component is truly disabled. User cannot toggle the checkbox on
and off.
> feat(checkbox.vue): make disabled checkbox truly disabled

- src/components/CheckBox/CheckBox.vue
With disabled option, the CheckBox component is truly disabled. User cannot toggle the checkbox on
> fix(checkbox.vue): make disabled checkbox truly disabled

- src/stylesheets/variables/_index.scss
> refactor: 使用しない色変数を削除

- package.json
github pagesでは、jekyllをデフォルトとしていて、`_`が先頭のファイルが配信されない。その関係で本番のみstorybookでエラーがでた。
明示的にjekyllでないことを伝えるoptionを設定。
参考: https://www.npmjs.com/package/gh-pages#optionsnojekyll
> bugfix: nojekyllのオプションを追加

- src/components/ContentLoader/ContentLoader.vue
Content LoaderのCircleにanimationのCSSを適応し忘れていたので修正しました
|before|after|
|---|---|
|![Kapture 2024-10-15 at 08 38 31](https://github.com/user-attachments/assets/4b0eaae3-d5eb-403f-b26a-a31fdf9e83f8)|![Kapture 2024-10-15 at 08 37 36](https://github.com/user-attachments/assets/a715b5d3-732a-461f-ba8f-572fe9288a18)|
> circleにanimationが適応されていなかったの修正

- src/components/ContentLoader/ContentLoader.vue
- src/components/TextInput/TextInput.vue
- src/stylesheets/variables/_index.scss
https://github.com/lapras-inc/scouty/issues/25828
|Before|After|
|---|---|
| <img width="810" alt="image" src="https://github.com/user-attachments/assets/1a9b1d4c-c991-427d-ab7f-543f62f5670f"> | <img width="817" alt="image" src="https://github.com/user-attachments/assets/5426a03b-191b-4ba4-aadf-ef2c5a5530f9"> |
- media-queryの指定をLAPRASに合わせて変更 & colorを追加
- TextInputの標準デザインを枠線ありに変更。その他微調整
- content-loaderの色を薄めに変更
> TextInputのデザイン修正

- package.json
node engineのバージョンをアップデート
- node engineバージョン変更
- `20.x` to `22.11`
- lapras-frontendのバージョン変更
- `0.3.5` to `0.3.6`
> chore: node engineを22.11にupdate

- package.json
`package.json`に記載するバージョンはrelease時にGitHub Actionにて採番されるため、masterを変更するとConflictが生じる。
https://github.com/lapras-inc/lapras-frontend/pull/284 で変更したversionを元の状態に戻す
> fix: packageのバージョンは自動採番のため、変更前に戻す
