lapras-inc/lapras-frontend

README.md, package.json, yarn.lock
`yarn storybook:deploy` でデプロイできる
=> StorybookをGitHub Pagesにデプロイできるようにした

src/components/FlatButton/FlatButton.stories.mdx, src/components/FlatButton/FlatButton.vue
=> コンポーネント追加 - FlatButton

src/components/TextInput/TextInput.stories.mdx, src/components/TextInput/TextInput.vue
=> コンポーネント追加 - TextInput

src/components/ToggleSwitch/ToggleSwitch.stories.mdx, src/components/ToggleSwitch/ToggleSwitch.vue
=> コンポーネント追加 - ToggleSwitch

src/components/TagLabel/TagLabel.stories.mdx, src/components/TagLabel/TagLabel.vue
=> コンポーネント追加 - TagLabel

src/components/EnhancedIconButton/EnhancedIconButton.stories.mdx, src/components/EnhancedIconButton/EnhancedIconButton.vue
=> コンポーネント追加 - EnhancedIconButton

src/components/RatingBar/RatingBar.stories.mdx, src/components/RatingBar/RatingBar.vue
=> コンポーネント追加 - RatingBar

src/components/ToggleSet/ToggleLabelSet.stories.mdx, src/components/ToggleSet/ToggleLabelSet.vue
=> コンポーネント追加 - ToggleLabelSet

src/components/CheckBox/CheckBox.vue, src/components/EnhancedIconButton/EnhancedIconButton.vue, src/components/FlatButton/FlatButton.vue, src/components/Modal/Modal.vue, src/components/Radio/Radio.vue, src/components/SelectBox/SelectBox.vue, src/components/ToggleLabelSet/ToggleLabelSet.vue, src/components/ToggleSwitch/ToggleSwitch.vue, src/components/Tooltip/Tooltip.vue, src/main.ts, src/stylesheets/_index.scss, src/stylesheets/mixins/_base-hover.scss, src/stylesheets/mixins/_index.scss, src/stylesheets/mixins/_inline-link.scss, src/stylesheets/variables/_index.scss, vue.config.js
以下の軽微な修正をしました 🙇 
- TooltipとRadioをexportし忘れていたので修正
- modalにz-indexを指定できるpropsを付ける
一応デフォルト10入れていますが、今後もっと大きな数が必要になるかもしれないので上書きできるようにpropsにしました
- ホバーを最近小瀧さんと作ったものに統一する
- Firefoxで高さがないモーダルも上つきになるバグ修正
=> コンポーネント追加リリース後微調整

src/components/ToggleLabelSet/ToggleLabelSet.stories.mdx, src/components/ToggleLabelSet/ToggleLabelSet.vue
max-widthが設定されていることで、flexbox内でのレイアウト時に要素が潰れてしまう問題があったので修正しました
=> [fix] ToggleLabelSetのmax-width

src/components/AvatarImg/AvatarImg.vue, src/components/FlatButton/FlatButton.vue, src/components/Icon/Icon.vue, src/components/RatingBar/RatingBar.vue, src/components/TagLabel/TagLabel.vue
computed関数をsetup内で使うと、storybookでは正しく動くのですが読み込み先でエラーが出るので、一旦使わないようにしました。
=> [fix] computed関数をsetup内で使うと読み込み先でエラーが出るので、一旦使わないようにする

src/components/Modal/Modal.vue
=> デザイン微調整 - モーダルの閉じるボタン

.github/workflows/npm-release.yml, .github/workflows/npm-test.yml
=> テスト実行をPRに限定 + deploy workflowをファイル分離

src/components/FlatButton/FlatButton.stories.mdx, src/components/FlatButton/FlatButton.vue
https://github.com/lapras-inc/scouty/issues/10806
=> ボタンコンポーネントの修正

src/components/FlatButton/FlatButton.stories.mdx, src/components/FlatButton/FlatButton.vue
=> feat(flatbutton): 点滅するバリエーション

src/components/TextInput/TextInput.stories.mdx, src/components/TextInput/TextInput.vue
`<TextInput v-on:focus="onFocus" />` のようなことを柔軟にやるための変更です。
=> textarea, input の v-on に外から触れるようにする

src/components/Modal/Modal.vue, src/components/TextInput/TextInput.vue
=> Release 20220303081543

src/components/TextInput/TextInput.stories.mdx, src/components/TextInput/TextInput.vue
https://github.com/lapras-inc/scouty/issues/13547
- 入力内容によってtextareaの高さが自動的に変わるようにしたい
- autoExpand、baseTextareaHeightのpropsを追加
- Storybookのcontrolsを使ってインタラクティブに状態を確認できるようにstoryを修正。
https://user-images.githubusercontent.com/11070996/157372892-19d37f01-f359-48e3-876d-13834c4a7007.mp4
=> feat: textareaを自動拡張するオプションを追加

.eslintrc.js, src/components/ProtectedLink/ProtectedLink.vue, src/components/TextInput/TextInput.vue
=> chore: eslintのerrorを修正

src/components/TextInput/TextInput.stories.mdx, src/components/TextInput/TextInput.vue
=> Release 20220309044630

CHANGELOG.md, package.json
This reverts commit c480f540516d34cb76a5a88c02b3fdcc839060cb.
手動でreleaseコマンドを打ってはいけなかったのでrevert
=> Revert "chore(release): 0.1.0"

.eslintrc.js, src/components/Modal/Modal.vue
=> fix(modal): ブラウザバックでスクロールがロックされる問題を修正

src/components/FlatButton/FlatButton.vue, src/components/SelectBox/SelectBox.vue, src/components/TextInput/TextInput.stories.mdx, src/components/ToggleSwitch/ToggleSwitch.vue
https://github.com/lapras-inc/lapras-frontend/issues/208
=> disable周りの修正 

vue.config.js
参考: https://github.com/lapras-inc/lapras-frontend/commit/38ddd8c9d15c9658c11b0314ab1e285ab766321d
=> fix(vue): build 時にパス解決が行えなくなっていた問題に対処 resolve #243

package.json, yarn.lock
vitest化で以下の問題に対処するために、peerDependenciesとdevDependenciesに移動しました
https://github.com/lapras-inc/scouty/issues/22005#issuecomment-2301256166
=> VueをpeerDependenciesへ

src/components/AvatarImg/AvatarImg.vue
closes https://github.com/lapras-inc/scouty/issues/26171
storybookで確認
before
after
=> AvatarImgで括弧や空白が入っている文字列でも正しく表示できるように修正

src/components/Radio/Radio.vue
disabled属性がinputに付いておらず、propとして渡しても効いていなかったのを修正しました。
=> fix(Radio): disabledが効いてなかったのを修正

src/components/ShortModal/ShortModal.vue
ShortModalにcloseOnClickOutside propを追加しました。
=> feat(shortmodal): add closeOnClickOutside prop

src/components/Modal/Modal.vue
[以前ShortModalにした対応](https://github.com/lapras-inc/lapras-frontend/pull/290)と同じです。
=> feat(Modal): add closeOnClickOutside prop
